export const CONSTANT_NEW = 'FILTER_NEW';
export const CONSTANT_OLD = 'FILTER_OLD';
export const CONSTANT_TRAVEL = 'FILTER_TRAVEL';
export const CONSTANT_URBAN = 'FILTER_URBAN';
export const CONSTANT_WEDDING = 'FILTER_WEDDING';
export const CONSTANT_PEOPLE = 'FILTER_PEOPLE';
export const CONSTANT_CONCERT = 'FILTER_CONCERT';
export const ACTION_TYPE_FILTER = 'ACTION_TYPE_FILTER';